version: '3'

services:
  app:
    image: ameixa
    container_name: ameixa_container
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MONGO_URI
    depends_on:
      - mongo
    ports:
      - 3001:3001
    volumes:
      - ./:/app

  mongo:
    image: mongo:5.0.5
    container_name: ameixa_database_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: